config/routes.rb
Rails.application.routes.draw do
  resources :beers

  root 'beers#index'
end

app/models/beer.rb
class Beer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :description, :consumption_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<div class="column-group gutters">
  <div class="all-50 small-100 tiny-100">
    <div class="ink-form">
      <%= form_for(@beer) do |f| %>
        <% if @beer.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>
            <ul>
              <% @beer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="control-group">
          <%= f.label :name %>
          <div class="control">
            <%= f.text_field :name %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :description %>
          <div class="control">
            <%= f.text_area :description %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :consumption_date %>
          <div class="control">
            <%= f.text_field(:consumption_date, id: "myDatePicker", class: "ink-datepicker") %>
          </div>
        </div>

        <div class="actions">
          <%= f.submit(class: 'ink-button') %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="all-50 small-100 tiny-100">
    <p>Wrap forms in the ink-form class</p>
  </div>
</div>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<div class="column-group horizontal-gutters">
  <div class="all-50 order-2">
    Example application for <%= link_to("ink.sapo.pt", "http://ink.sapo.pt/", target: "_blank") %> using the <%= link_to("ink-3-rails", "https://github.com/mutablestate/ink3-rails", target: "_blank") %> gem
  </div>
  <div class="all-50 order-r1">
    <h2>Listing beers</h2>
    <table class="ink-table hover">
      <thead>
        <tr>
          <th class="align-left">Name</th>
          <th class="align-left">Description</th>
          <th class="align-left">Consumption Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @beers.each do |beer| %>
          <tr>
            <td><%= beer.name %></td>
            <td><%= beer.description %></td>
            <td><%= beer.consumption_date %></td>
            <td>
              <%= link_to('Show', beer, class: 'ink-button blue') %>
              <%= link_to('Edit', edit_beer_path(beer), class: 'ink-button green') %>
              <%= link_to('Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'ink-button red') %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br />
    <%= link_to('New Beer', new_beer_path, class: 'ink-button') %>
  </div>
</div>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<div class="column-group horizontal-gutters">
  <div class="all-33 order-3">
    <p>
      <strong>Name:</strong>
      <%= @beer.name %>
    </p>
  </div>
  <div class="all-33 order-1">
    <p>
      <strong>Description:</strong>
      <%= @beer.description %>
    </p>
  </div>
  <div class="all-33 order-2">
    <p>
      <strong>Consumption date:</strong>
      <%= @beer.consumption_date %>
    </p>
  </div>
</div>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

app/views/layouts/_navigation.html.erb
<div id="topbar">
  <nav class="ink-navigation ink-grid ie7">
    <ul class="menu horizontal black push-left medium-push-center small-push-center tiny-push-center">

      <li class="hide-all show-tiny show-small show-medium">
        <button class="fa fa-bars left-drawer-trigger"></button>
      </li>
    <li class="logoPlaceholder">
      <%= link_to("Ink 3 Rails", "#", class: "logoPlaceholder") %>
    </li>
    </ul>
    <ul class="menu horizontal black push-right hide-small hide-tiny hide-medium">
      <li class="heading"><%= link_to("Home", root_path) %></li>
      <li><%= link_to("Beers", beers_path) %></li>
    </ul>
  </nav>
</div>
<div class="left-drawer">
  <ul>
    <li>
      <a href="http://ink.sapo.pt/ui-elements/" title="UI Elements">UI Elements</a>
    </li>
    <li>
      <a href="http://ink.sapo.pt/javascript/" title="Javascript">Javascript</a>
    </li>
    <li>
      <a href="http://ink.sapo.pt/cookbook/" title="Cookbook">Cookbook</a>
    </li>
    <li>
      <a href="http://ink.sapo.pt/glossary/" title="Glossary">Glossary</a>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ink 3 Rails Demo</title>
  <meta name="description" content="">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="ink-drawer">
  <%= render 'layouts/navigation' %>
  <div id="content" class="content-drawer">
    <section class="ink">
      <div class="ink-grid">
        <header>
          <h1>
            Ink 3 Rails Example
          </h1>
        </header>
      <%= yield %>
    </section>
    <footer></footer>
    <section class="copyright">
      <div class="ink-grid">
        <div class="copyright push-right">
          Try the <%= link_to("ink3-rails", "https://github.com/mutablestate/ink3-rails") %> gem
        </div>
      </div>
    </section>
  </div>
  <a href="https://github.com/mutablestate/ink3-rails-demo">
    <img style="position: absolute; top: 0; right: 0; border: 0; z-index: 100;" src="https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png">
  </a>
</body>
</html>